version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:30"
    target-branch: "main"
    allow:
      - dependency-name: "@api3/*"
      - dependency-name: "@nodary/*"
    groups:
      api3:
        patterns:
          - "@api3/*"
          - "@nodary/*"
      others:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/viewer"
    schedule:
      interval: "daily"
      time: "12:30"
    target-branch: "main"
    allow:
      - dependency-name: "@api3/*"
      - dependency-name: "@nodary/*"
    groups:
      api3:
        patterns:
          - "@api3/*"
          - "@nodary/*"
      others:
        patterns:
          - "*"
