version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:15"
    target-branch: "main"
    allow:
      - dependency-name: "@api3/*"
      - dependency-name: "@nodary/*"
    ignore:
      - dependency-name: "*"
        dependency-type: "devDependencies"
    groups:
      development-dependencies:
        patterns:
          - "@api3/*"
          - "@nodary/*"
        exclude-patterns:
          - "*"
