version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:55"
    target-branch: "main"
    packages:
      - name: "@api3/chains" # Replace with the actual package name
        allowed_updates:
          - "major"
          - "minor"
          - "patch"
