version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:05"
    target-branch: "main"
    groups:
      development-dependencies:
        patterns:
          - "@api3/*"
          - "@nodary/*"
