version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    target-branch: "main"
    allow:
        dependency-name: "@api3/*"
        dependency-name: "@nodary/*"
    ignore:
      - dependency-name: '*'
    groups:
      development-dependencies:
        patterns:
          - "@api3/*"
          - "@nodary/*"
        exclude-patterns:
          - "*"
