version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:20"
    target-branch: "main"
    allow:
      - dependency-name: "@api3/*"
      - dependency-name: "@nodary/*"
      - dependency-type: "production"
    groups:
      development-dependencies:
        patterns:
          - "@api3/*"
          - "@nodary/*"
        exclude-patterns:
          - "*"
