packages:
  - "."
  - "viewer"

allowBuilds:
  '@swc/core': false
  unrs-resolver: false

# See: https://pnpm.io/supply-chain-security
blockExoticSubdeps: true
minimumReleaseAge: 20160 # 14 days

minimumReleaseAgeExclude:
  - '@api3/*'
  # Renovate security update: vite@8.0.16
  - vite@8.0.16

resolution-mode: highest
