name: dispatch receiver

on:
    repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: dispatch trigger
      if : github.event.action == 'release'
      run: |
        echo "repository_dispatch triggered"