# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Fetch Logos from Dropbox

on:
  pull_request:
    branches: [ main ]

jobs:
  pack-local-package:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'yarn'
      - name: Install Packages
        run: yarn install
      - name: Build Package
        run: yarn build-svg
      - name: Fetch Logos
        run: yarn fetch --DROPBOX ${{ secrets.DROPBOX }}
      - uses: stefanzweifel/git-auto-commit-action@v5