# https://github.com/changesets/action
name: Release

on:
  push:
    branches:
      - production

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_CONFIG_PROVENANCE: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.12.1
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm run build

      - name: Create Release
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
          commit: "ci: release logos package"
          title: "ci: release logos package"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create pull request
        if: steps.changesets.outputs.published == 'true'
        run: gh pr create -B main -H production --title 'Merge production into main' --body 'Merges production into main'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}